In [1]:
pip install numpy

In [2]:
import numpy as np
marks = np.array([78, 65, 89, 56, 92])
print("Input marks:", marks)
print("Number of dimensions:", marks.ndim)
print("Shape:", marks.shape)
print("Size:", marks.size)
print("Data type:", marks.dtype)

Input marks: [78 65 89 56 92]
Number of dimensions: 1
Shape: (5,)
Size: 5
Data type: int64


In [3]:
import numpy as np
marks = np.array([72, 85, 64, 90, 76])
print("Input marks:", marks)
print("First student's mark:", marks[0])
print("Third student's mark:", marks[2])
print("Last student's mark:", marks[-1])
print("First three students:", marks[:3])
print("Second to fourth students:", marks[1:4])
print("Last two students:", marks[-2:])

Input marks: [72 85 64 90 76]
First student's mark: 72
Third student's mark: 64
Last student's mark: 76
First three students: [72 85 64]
Second to fourth students: [85 64 90]
Last two students: [90 76]


In [4]:
import numpy as np
marks = np.array([
    78, 85, 90,
    65, 72, 80,
    88, 91, 84,
    56, 62, 70,
    95, 89, 92
])
print("Original array:")
print(marks)
matrix = marks.reshape(5, 3)
print("\nReshaped matrix (5 students x 3 subjects):")
print(matrix)

Original array:
[78 85 90 65 72 80 88 91 84 56 62 70 95 89 92]

Reshaped matrix (5 students x 3 subjects):
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]


In [5]:
import numpy as np
internal = np.array([20, 18, 22, 19, 21])
external = np.array([65, 70, 60, 68, 72])
print("Internal marks:", internal)
print("External marks:", external)
final_marks = internal + external
print("Final marks:", final_marks)

Internal marks: [20 18 22 19 21]
External marks: [65 70 60 68 72]
Final marks: [85 88 82 87 93]


In [6]:
import numpy as np
marks = np.array([45, 78, 56, 32, 91])
print("Input marks:", marks)
mask = marks >= 50
print("Boolean mask:", mask)
print("Students scoring 50 or above:", marks[mask])
print("Student positions:", np.where(mask)[0] + 1)

Input marks: [45 78 56 32 91]
Boolean mask: [False  True  True False  True]
Students scoring 50 or above: [78 56 91]
Student positions: [2 3 5]


In [7]:
import numpy as np
marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])
print("Marks matrix:")
print(marks)
average = np.mean(marks, axis=1)
print("\nAverage marks of each student:")
print(average)

Marks matrix:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]

Average marks of each student:
[84.33333333 72.33333333 87.66666667 62.66666667 92.        ]


In [8]:
import numpy as np
marks = np.array([67, 82, 91, 74, 58])
print("Input marks:", marks)
total = np.sum(marks)
average = np.mean(marks)
highest = np.max(marks)
lowest = np.min(marks)
std_deviation = np.std(marks)
print("Total:", total)
print("Average:", average)
print("Highest:", highest)
print("Lowest:", lowest)
print("Standard deviation:", std_deviation)

Input marks: [67 82 91 74 58]
Total: 372
Average: 74.4
Highest: 91
Lowest: 58
Standard deviation: 11.46472851837321


In [9]:
import numpy as np
marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])
print("Marks matrix:")
print(marks)
subject_total = np.sum(marks, axis=0)
print("\nTotal marks in each subject:")
print(subject_total)

Marks matrix:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]

Total marks in each subject:
[382 399 416]


In [10]:
import numpy as np
marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])
print("Marks matrix:")
print(marks)
student_total = np.sum(marks, axis=1)
print("\nTotal marks obtained by each student:")
print(student_total)

Marks matrix:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]

Total marks obtained by each student:
[253 217 263 188 276]


In [11]:
import numpy as np
marks = np.array([245, 278, 219, 290, 256])
print("Original total marks:", marks)
sorted_marks = np.sort(marks)[::-1]
ranking = np.argsort(marks)[::-1]
print("Marks in descending order:", sorted_marks)
print("\nRanking:")
for rank, index in enumerate(ranking, start=1):
    print("Rank", rank, "- Student", index + 1,
          "- Marks:", marks[index])

Original total marks: [245 278 219 290 256]
Marks in descending order: [290 278 256 245 219]

Ranking:
Rank 1 - Student 4 - Marks: 290
Rank 2 - Student 2 - Marks: 278
Rank 3 - Student 5 - Marks: 256
Rank 4 - Student 1 - Marks: 245
Rank 5 - Student 3 - Marks: 219


In [12]:
import numpy as np
marks = np.array([85, 92, 85, 76, 92])
print("Input marks:", marks)
unique_marks = np.unique(marks)
print("Unique marks:", unique_marks)

Input marks: [85 92 85 76 92]
Unique marks: [76 85 92]


In [13]:
import numpy as np
marks = np.array([78, 85, np.nan, 92, 67])
print("Input marks:", marks)
average = np.nanmean(marks)
print("Average excluding missing mark:", average)

Input marks: [78. 85. nan 92. 67.]
Average excluding missing mark: 80.5


In [14]:
import numpy as np
marks = np.array([95, 82, 74, 61, 45])
print("Input marks:", marks)
grades = np.select(
    [
        marks >= 90,
        marks >= 80,
        marks >= 70,
        marks >= 60
    ],
    [
        "A",
        "B",
        "C",
        "D"
    ],
    default="F"
)
print("Grades:", grades)

Input marks: [95 82 74 61 45]
Grades: ['A' 'B' 'C' 'D' 'F']


In [15]:
import numpy as np
marks = np.random.randint(0, 101, size=5)
print("Randomly generated marks:", marks)
print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Standard deviation:", np.std(marks))

Randomly generated marks: [  8 100  81  67  88]
Total: 344
Average: 68.8
Highest: 100
Lowest: 8
Standard deviation: 32.22049037491515


In [16]:
import numpy as np
marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])
print("Marks of five students:")
print(marks)
total = np.sum(marks, axis=1)
average = np.mean(marks, axis=1)
highest = np.max(marks, axis=1)
lowest = np.min(marks, axis=1)
class_average = np.mean(marks)
print("\nTotal marks of each student:")
print(total)
print("\nAverage marks of each student:")
print(average)
print("\nHighest mark of each student:")
print(highest)
print("\nLowest mark of each student:")
print(lowest)
print("\nClass average:", class_average)
above_average = np.where(average > class_average)[0] + 1
print("\nStudents performing above class average:")
print(above_average)

Marks of five students:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]

Total marks of each student:
[253 217 263 188 276]

Average marks of each student:
[84.33333333 72.33333333 87.66666667 62.66666667 92.        ]

Highest mark of each student:
[90 80 91 70 95]

Lowest mark of each student:
[78 65 84 56 89]

Class average: 79.8

Students performing above class average:
[1 3 5]
